#!/usr/bin/env python3
"""Verysset identity generator: the circle symbol (three nested isometric cubes) + the VERYSSET wordmark.

Symbol. A flat #FFD400 circle carrying one ink mark, three concentric isometric cubes on one center:
  1. outer cube, OPEN frame: its silhouette (a thick hexagon ring) and its three front edges, drawn as the
     spokes that cross the open space and meet the middle cube at its corners; faces left open
  2. middle cube, SOLID faces: its three visible faces, each an L band stopping one gap short of the core
  3. inner cube, the core: three small solid faces around the shared front corner
  One narrow channel along the three front edges splits the faces of the middle cube and the core.

Exact 30 degree isometric projection, computed, never eyeballed:
  x -> (cos30, sin30), y -> (-cos30, sin30), z -> (0, -1)   (screen y points down)
A cube of edge a centered on the mark projects to a regular hexagon of circumradius a, and its front corner
lands on the center. Every visible face is the affine image of the unit square spanned by two of the three
edge vectors leaving that corner (upper right, upper left, down). A concentric cube of edge f is simply the
square [0, f] in those face coordinates, so every band, gap and channel is a rectangle in face units and
lands on screen with ONE uniform perpendicular weight: face units * R * sin120 (= face units * R * cos30).

The mark is a single nonzero path: every filled shape winds one way, the ring's inner hexagon the other,
and the spokes overlap the ring and the middle faces, so no two shapes abut (no hairline seams). Flat,
no stroke, no gradient. The wordmark is Clash Display Semibold converted to outlines, glyphs, scale and
optical tracking unchanged from the previous identity.

FROZEN (round 10): the shipped set in assets/ is the source of truth; build.py no longer runs this script.
Outputs: assets/logo-symbol.svg (circle colorway), assets/logo-symbol-yellow.svg (yellow mark, transparent),
         assets/favicon.svg (favicon cut: larger, bolder), assets/logo.svg, assets/logo-dark.svg,
         assets/logo.json (metrics for build.py), plus the legacy brand names (assets/verysset-logo.svg,
         assets/verysset-logo-dark.svg, verysset-logo.svg) so no old square survives behind an old URL.
"""
import os, json, math
from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.pens.boundsPen import BoundsPen

ROOT = os.path.dirname(os.path.abspath(__file__))
YELLOW, INK, WHITE = "#FFD400", "#0A0A09", "#FFFFFF"
WORD = "VERYSSET"

C30 = math.cos(math.pi / 6)                       # 0.8660254
# unit edge vectors leaving the front corner, in screen space (y down)
AX = {"ur": (C30, -0.5), "ul": (-C30, -0.5), "dn": (0.0, 1.0)}
FACES = (("ur", "ul"), ("ur", "dn"), ("ul", "dn"))   # top, right, left

# Symbol on a 512u square, circle r 256. R = outer hexagon circumradius. Everything else in face units
# (1 = outer cube edge): w frame weight, m middle cube edge, c channel, g gap around the core, core edge.
S = 512
MARK = {"R": 190.0, "w": .14, "m": .62, "c": .07, "g": .07, "core": .33}
# favicon cut: a larger mark, bolder frame, wider open space and gaps, so 16 px still shows frame and core
FAV = {"R": 230.0, "w": .18, "m": .60, "c": .09, "g": .09, "core": .34}
EPS = .012        # overlap of spokes into ring and middle faces, kills anti-aliasing seams

# Wordmark (unchanged): Clash Display Semibold, cap height 56u, optical pair spacing.
CAP = 56
TRACK = 18.5
PAIR = {"VE": .56, "ER": .88, "RY": .50, "YS": .60, "SS": .90, "SE": .96, "ET": .56}
# Lockup: a circle carries less mass than a square of the same height (pi/4 of it), so it is drawn 8 %
# taller than the old 96u square, and the caps are centered on it optically instead of standing on its base.
D = 104
GAP = 30          # circle edge to the V: a touch under the old 32u, the circle's edge falls away from its equator

NOTE = ("<!-- VERYSSET identity. Flat yellow circle carrying three nested isometric cubes (open frame, solid "
        "faces, solid core), exact 30 degree projection; wordmark Clash Display Semibold as outlines. "
        "Generated by logogen.py. -->")


def fmt(v):
    s = ("%.2f" % v).rstrip("0").rstrip(".")
    return "0" if s in ("-0", "") else s


def _area(pts):
    return sum(pts[i][0] * pts[i - 1][1] - pts[i - 1][0] * pts[i][1] for i in range(len(pts))) / 2.0


def _poly(pts, fill=True):
    if (_area(pts) > 0) != fill:
        pts = pts[::-1]
    return "M" + "L".join("%s %s" % (fmt(x), fmt(y)) for x, y in pts) + "Z"


def hexagon(cx, cy, r):
    """Silhouette of a centered cube of edge r (vertices from the top, clockwise)."""
    return [(cx + r * math.cos(math.radians(a)), cy + r * math.sin(math.radians(a)))
            for a in (-90, -30, 30, 90, 150, 210)]


def mark_path(cx, cy, R, w, m, c, g, core, eps=EPS):
    """The nested cube mark as one nonzero path, centered on (cx, cy), outer hexagon circumradius R."""
    def pt(face, s, t):
        a, b = AX[face[0]], AX[face[1]]
        return (cx + R * (s * a[0] + t * b[0]), cy + R * (s * a[1] + t * b[1]))

    h, q = c / 2.0, core + g
    assert h < core < q < m < 1 - w, "mark proportions leave no room for the three cubes"
    sub = [_poly(hexagon(cx, cy, R)), _poly(hexagon(cx, cy, (1 - w) * R), fill=False)]      # 1 open frame ring
    for f in FACES:
        sub.append(_poly([pt(f, q, h), pt(f, m, h), pt(f, m, m), pt(f, h, m),
                          pt(f, h, q), pt(f, q, q)]))                                        # 2 middle face, L band
        sub.append(_poly([pt(f, h, h), pt(f, core, h), pt(f, core, core), pt(f, h, core)]))  # 3 core face
    for ax in ("ur", "ul", "dn"):                                                           # 1 front edges, spokes
        fa, fb = [f for f in FACES if ax in f]

        def fp(f, s, t):                     # s along the spoke's axis, t along the face's other axis
            return pt(f, s, t) if f[0] == ax else pt(f, t, s)
        sub.append(_poly([fp(fa, m - eps, w / 2), fp(fa, 1 - w / 2, w / 2), fp(fb, 1 - w / 2, w / 2),
                          fp(fb, m - eps, w / 2),
                          (cx + (m - eps) * R * AX[ax][0], cy + (m - eps) * R * AX[ax][1])]))
    return " ".join(sub)


def mark(cx, cy, scale=1.0, p=MARK):
    return mark_path(cx, cy, p["R"] * scale, p["w"], p["m"], p["c"], p["g"], p["core"])


def symbol_svg(kind="circle"):
    """circle = yellow circle + ink mark; yellow = yellow mark on transparent; favicon = circle, bold cut."""
    d = mark(S / 2, S / 2, 1.0, FAV if kind == "favicon" else MARK)
    body = ('<path fill="%s" d="%s"/>' % (YELLOW, d) if kind == "yellow" else
            '<circle cx="256" cy="256" r="256" fill="%s"/>\n<path fill="%s" d="%s"/>' % (YELLOW, INK, d))
    return ('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {s} {s}" width="{s}" height="{s}" role="img" '
            'aria-label="VERYSSET">\n{note}\n<title>VERYSSET</title>\n{body}\n</svg>\n'
            ).format(s=S, note=NOTE, body=body)


def wordmark_paths(x0, baseline, cap=CAP, track=TRACK, weight="Semibold", pair=PAIR):
    font = TTFont(os.path.join(ROOT, "assets", "fonts", "ClashDisplay-%s.otf" % weight))
    gs = font.getGlyphSet()
    cmap = font.getBestCmap()
    k = cap / float(font["OS/2"].sCapHeight)
    paths, cursor = [], x0
    for i, ch in enumerate(WORD):
        gl = gs[cmap[ord(ch)]]
        bp = BoundsPen(gs)
        gl.draw(bp)
        xmin, _, xmax, _ = bp.bounds
        pen = SVGPathPen(gs, ntos=fmt)
        gl.draw(TransformPen(pen, (k, 0, 0, -k, cursor - k * xmin, baseline)))
        paths.append(pen.getCommands())
        cursor += k * (xmax - xmin)
        if i < len(WORD) - 1:
            cursor += track * pair.get(WORD[i:i + 2], 1.0)
    return paths, cursor


def lockup(ink):
    r = D / 2.0
    words, w = wordmark_paths(D + GAP, r + CAP / 2.0)
    return ('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w} {h}" width="{w}" height="{h}" '
            'role="img" aria-label="VERYSSET">\n{note}\n<title>VERYSSET</title>\n'
            '<circle cx="{r}" cy="{r}" r="{r}" fill="{y}"/>\n'
            '<path fill="{k}" d="{mk}"/>\n<path fill="{ink}" d="{word}"/>\n</svg>\n'
            ).format(w=fmt(w), h=fmt(D), r=fmt(r), note=NOTE, y=YELLOW, k=INK, ink=ink,
                     mk=mark(r, r, D / float(S)), word=" ".join(words)), w, D


def metrics(w, h):
    p = MARK
    return {"lockup_w": round(w, 2), "lockup_h": h, "circle": D, "gap": GAP, "cap_height": CAP,
            "cap_line": round(D / 2.0 - CAP / 2.0, 2), "baseline": round(D / 2.0 + CAP / 2.0, 2),
            "symbol_viewbox": S, "mark_R": p["R"], "mark_ratio": round(2 * p["R"] / S, 4),
            "frame": p["w"], "middle": p["m"], "core": p["core"], "gap_g": p["g"], "channel": p["c"],
            "frame_px": round(p["w"] * p["R"] * C30, 2), "gap_px": round(p["g"] * p["R"] * C30, 2)}


def main(quiet=False):
    light, w, h = lockup(INK)
    dark, _, _ = lockup(WHITE)
    for rel, txt in [("assets/logo.svg", light), ("assets/logo-dark.svg", dark),
                     ("assets/logo-symbol.svg", symbol_svg("circle")),
                     ("assets/logo-symbol-yellow.svg", symbol_svg("yellow")),
                     ("assets/favicon.svg", symbol_svg("favicon")),
                     ("assets/verysset-logo.svg", light), ("assets/verysset-logo-dark.svg", dark),
                     ("verysset-logo.svg", light)]:
        with open(os.path.join(ROOT, rel), "w", encoding="utf-8") as f:
            f.write(txt)
    meta = metrics(w, h)
    with open(os.path.join(ROOT, "assets", "logo.json"), "w", encoding="utf-8") as f:
        f.write(json.dumps(meta, indent=1) + "\n")
    if not quiet:
        print("logogen: " + json.dumps(meta))
    return meta


if __name__ == "__main__":
    import sys
    # Round 10: the shipped circle identity in assets/ is frozen (build.py reads assets/logo.json and never
    # calls main()). This revision of the mark parameters differs from the shipped set, so overwriting the
    # published logo files has to be deliberate.
    if "--force" not in sys.argv:
        raise SystemExit("logogen: assets/ logo set is frozen (round 10). Rerun with --force to regenerate it.")
    main()
