#!/usr/bin/env python3
"""Verysset identity generator: the flat square mark + the VERYSSET wordmark as pure vectors.

Concept, the Verified Unit. A flat, solid #FFD400 square (the real asset). Its top right corner
is set apart as one exact unit by a thin L shaped channel of negative space (the verified token
carved from the asset). The lower edge of that channel is the cap line of the wordmark, so the
symbol and the name are built on one geometry: shared baseline, shared cap line, one unit grid.

Everything is flat. No gradient, no 3D, no stroke. The wordmark is Clash Display Semibold
converted to outlines, so every SVG is self contained and renders identically without fonts.

Grid (u = one unit of a 96u square, everything on an 8u rhythm):
  square 96u, token unit 32u (one third), channel 8u, cap line at 40u, cap height 56u,
  clear space between square and wordmark = one unit (32u).

Outputs: assets/logo.svg, assets/logo-dark.svg, assets/logo-symbol.svg, assets/favicon.svg,
         assets/logo.json (metrics for build.py), plus the legacy brand file names
         (assets/verysset-logo.svg, assets/verysset-logo-dark.svg, verysset-logo.svg) so no old
         cube survives behind an old URL.
"""
import os, json
from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.pens.boundsPen import BoundsPen

ROOT = os.path.dirname(os.path.abspath(__file__))
YELLOW, YELLOW_D, INK, WHITE = "#FFD400", "#E6BF00", "#0A0A09", "#FFFFFF"
WORD = "VERYSSET"

SQ, BLK, CH = 96, 32, 8
TRACK = 18.5      # ink to ink gap between two straight stems (about a third of the cap height)
# optical spacing per pair: 1.0 = straight stem beside straight stem; diagonals and open
# counters sit closer so the tracking reads even, not mechanical
PAIR = {"VE": .56, "ER": .88, "RY": .50, "YS": .60, "SS": .90, "SE": .96, "ET": .56}

NOTE = ("<!-- VERYSSET identity, the Verified Unit. Flat square with its token unit and channel on a "
        "96u grid; wordmark Clash Display Semibold as outlines. Generated by logogen.py. -->")


def fmt(v):
    s = ("%.2f" % v).rstrip("0").rstrip(".")
    return "0" if s in ("-0", "") else s


def symbol_path(sq=SQ, blk=BLK, ch=CH):
    """Body = the square minus the corner unit and its channel. Second subpath = the unit."""
    return ("M0 0H{c}V{t}H{s}V{s}H0Z M{b0} 0H{s}V{blk}H{b0}Z"
            .format(c=fmt(sq - blk - ch), t=fmt(blk + ch), s=fmt(sq), blk=fmt(blk), b0=fmt(sq - blk)))


def wordmark_paths(x0, sq=SQ, blk=BLK, ch=CH, track=TRACK, weight="Semibold", pair=PAIR):
    font = TTFont(os.path.join(ROOT, "assets", "fonts", "ClashDisplay-%s.otf" % weight))
    gs = font.getGlyphSet()
    cmap = font.getBestCmap()
    k = (sq - blk - ch) / float(font["OS/2"].sCapHeight)   # caps stop on the channel edge
    paths, cursor = [], x0
    for i, c in enumerate(WORD):
        g = gs[cmap[ord(c)]]
        bp = BoundsPen(gs)
        g.draw(bp)
        xmin, _, xmax, _ = bp.bounds
        pen = SVGPathPen(gs, ntos=fmt)
        g.draw(TransformPen(pen, (k, 0, 0, -k, cursor - k * xmin, sq)))
        paths.append(pen.getCommands())
        cursor += k * (xmax - xmin)
        if i < len(WORD) - 1:
            cursor += track * pair.get(WORD[i:i + 2], 1.0)
    return paths, cursor


def lockup(ink, sq=SQ, blk=BLK, ch=CH, track=TRACK, weight="Semibold", pair=PAIR):
    words, w = wordmark_paths(sq + blk, sq, blk, ch, track, weight, pair)
    h = sq + 1                                    # 1u of room for the S overshoot
    return ('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w} {h}" width="{w}" height="{h}" '
            'role="img" aria-label="VERYSSET">\n{note}\n<title>VERYSSET</title>\n'
            '<path fill="{y}" d="{sym}"/>\n<path fill="{ink}" d="{word}"/>\n</svg>\n'
            ).format(w=fmt(w), h=fmt(h), note=NOTE, y=YELLOW, sym=symbol_path(sq, blk, ch),
                     ink=ink, word=" ".join(words)), w, h


def symbol():
    return ('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 96 96" width="96" height="96" '
            'role="img" aria-label="VERYSSET">\n%s\n<title>VERYSSET</title>\n'
            '<path fill="%s" d="%s"/>\n</svg>\n' % (NOTE, YELLOW, symbol_path()))


def main(quiet=False):
    light, w, h = lockup(INK)
    dark, _, _ = lockup(WHITE)
    sym = symbol()
    for rel, txt in [("assets/logo.svg", light), ("assets/logo-dark.svg", dark),
                     ("assets/logo-symbol.svg", sym), ("assets/favicon.svg", sym),
                     ("assets/verysset-logo.svg", light), ("assets/verysset-logo-dark.svg", dark),
                     ("verysset-logo.svg", light)]:
        with open(os.path.join(ROOT, rel), "w", encoding="utf-8") as f:
            f.write(txt)
    meta = {"lockup_w": round(w, 2), "lockup_h": h, "square": SQ, "unit": BLK, "channel": CH,
            "cap_line": BLK + CH, "cap_height": SQ - BLK - CH, "clear_space": BLK}
    with open(os.path.join(ROOT, "assets", "logo.json"), "w", encoding="utf-8") as f:
        f.write(json.dumps(meta, indent=1) + "\n")
    if not quiet:
        print("logogen: " + json.dumps(meta))
    return meta


if __name__ == "__main__":
    main()
